dist: trusty
language: groovy
branches:
  except:
    - /^\\d+\\.\\d+\\.\\d+/
jdk:
  - oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
  - git config --global user.email "erwan@saagie.com"
  - git config --global user.name "erwan"
  - git remote set-url origin git@github.com:saagie/gradle-saagie-plugin.git
  - git config remote.origin.fetch refs/heads/*:refs/remotes/origin/*
  - openssl aes-256-cbc -K $encrypted_837e0722fe3d_key -iv $encrypted_837e0722fe3d_iv -in keys.tar.enc -out keys.tar -d
  - tar xvf keys.tar
  - mv id_rsa_travis ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - cp -fv config ~/.ssh/config
  - echo signing.password=$gpg_pass >> ~/.gradle/gradle.properties
  - echo nexusName=$SONATYPE_USERNAME >> ~/.gradle/gradle.properties
  - echo nexusPassword=$SONATYPE_PASSWORD >> ~/.gradle/gradle.properties
  - echo gradle.publish.key=$GRADLE_PUBLISH_KEY >> ~/.gradle/gradle.properties
  - echo gradle.publish.secret=$GRADLE_PUBLISH_SECRET >> ~/.gradle/gradle.properties
  - wget https://services.gradle.org/distributions/gradle-4.4.1-bin.zip
  - unzip gradle-4.4.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.4.1
  - export PATH=$GRADLE_HOME/bin:$PATH
script:
  - gradle test --stacktrace
  - if [ ${TRAVIS_BRANCH} = "master" ]; then
      git checkout master;
      gradle release -Prelease.useAutomaticVersion=true --stacktrace;
      gradle closeAndReleaseRepository;
    else
      gradle uploadArchive --stacktrace;
    fi
env:
  global:
    - secure: YxpgwCHzKY11ukJktkcpYidxPf63CdmwY78Wi8KROv/8glRc8NKmFNveKV3nq3el0TpsSMh36GVcFx0Uz7McDEPd9sgKByGq2rKoocULIhhc3e8brtgoOMsRPi3sLtodXPCvjXm0DRDaV6WfFupSB7z6x9SlvdUl58sA/cCKMOSz5mSLXJ9qeF2r0YxrS+K0pGUR+A1KS4A/5dYFHLMVGslYH4OyxLGM3k+IKv1eHNRtDHLS6XVf8UB40HQRFQVqeki+JORuvBPp8iVqNq5SUtzg6P4B8jpoC16xy7BEgF1MssAxCLXsaHIm39YDxCH5VF6n5IleMlCLaZ1m5RKlqpO9WTWMP7eY9Frq7a38rjBoRWBpO6NHW2nVSws75m2Q5s65K64jzJgqDvQgHR77vk0Bo64xGFn0XRKjC9/zb/i6b+xKfbmVhlMbngRhr7ijB4gxJMkkh1bQPdt0vJJT75V5m3i4sk6cZ8Qbo+NV+WH5O979lqN9ppbkon6+PuVgJLVeSMGfL3eUmKJ06PKo65YiN86u+DTt7DIY9Toj3QqcesjRKXPo0gpcozgtPMDDwW80+3CtslFv7xm23BtORg4YNSJKbMCanUbe8RYXoRRjuNJOqshF8NjLXQKy3XjkELRpStUUrddHU5hczGYgS/rihAlcM0HYN+IoAEjiXj8=
    - secure: YZGH0YEtIssXgeD40SbIzNW+4bjYaU+e0H9msI3/ohfmfQFTdCWl48qKIEkuFt/hh/SemYwDwd1cXBVXtNIiuVKydbocp8C3N4D8S4AWglBAnzrRop1b1hy0cL7msiRuw4QG5Hu8RDk+fGsaCXSNdWAGkQlsMqX1yz8POcU7yoLxwHKAyrnIC9MKaMyCJBOJDDaM1W3KNZDndWsmaPLvAeAWEskxgG94FnS64bUEiW5wIRASGuMXBaK1iZZ62DZbubexwyhfG631/lvPgSg0ZMbMSN/YUI7FK6k7wMAVI1oSPLBEz1kqqp7q2YM30Ul5HV9lqTjuI0y6nMXmB7iCceivmv/ZqP3zYutrPE04wA19CaQqIhziZDzBCi7bcrBbfw3jemFnfeyoItXtzV0qs5fvCD1tRzY10kqiHtd8uX/wNxAX4sfvxFEKXvGuTo8HMTj95RylJXj0yC7Ra2LPRhLn/M7FKj7F+LvmwHra1ZBL0kWFfMoLeqo1LjK1V5X3xKKLb0e0c9tjzy3PD1nWY95mgnkCAOe1MeeEGxPc4ZoEdf1o23ICZczvjmh0qPcYO5KKL4Bhhk5BKd87MC74FJoAs4Bn91AUDPpS0OvF3nk2QNytKdVCe7lIbSYXY/KIc4isR0r0hkwxGmtTTQDaw1HvxQ04njboGxT4y89oZJ8=
    - secure: Gq8jdV9UtcBE+a4m9RFdSR5XIOdR0rvPU4XClUU6cZkn6GeKAli6ptGBumZo9rdnsEgKfyQ3tk2vE0W62ebtQlJnF1ZPl0XkefRfDOamVTGFXVwAclKhwh/rsCqNEpshqy71Dir4OVhjRmyZll4qpLQ4zJVd5EcJ0cv/RxObZ8bcVNfRhnik8gBVmQQcMMu0EWUi2qEXSygvyiUid1L+RhhfoXZv36Vsr6d/HaVcgcNZUEqboxWHcx14tEafTNkymDfxHutpOzNX/SDSzTBpaiINugd7qe5ZJ0OufOJ0f3tidf55icMrHLARRCUYUolhjPGj8OhCjOdUF44sdV5r+7+kIgOUMYxodFcdwaNLnzMeksmuf9fR5gnsn9JIJrSrBPFFuAzBXsoVg4d8qqZWc7/+SZBKx5DWQWFEQ9gLmpve3WwBlfQO8e0OTGZcfDNi69reiUk6UqDyCkERgzrhbkAp9/mtyE8Uz7DotdKkInuBoFu00rcm+9feFTAW9EzCBY9pZaIKxUHX4/81aWN14Su66EEpu5/5SEW2ecnMAFqMeDOqulGJ9nN9qaRUVGs69Xj6d7AuJwNFtjdoJ5kuBJUm0zAEvFRNC3gCi8s+m5/enUOJ/zLF9TtmU+PUsqEKj4btLliuMjg8TwnFrP/OhjmQwPyXobG742+D0DPVcu4=
    - secure: TlOyzNJpA0IFjKEldETw9x1OsY3ZP4eNv7XTylkWYQun0nidyMaDRsX5todZ5Z9Tac3PKUb9AUM2IkeTExoxx+tcGBfp/Pf9nq96mHYcllRMhPPd4G5uNXqNQhBctYWKBUpkWYaUKmGI6KwSsmerE52yDsG9Qy+kwzYh31fPDzRsznK+4yJgR07tGunvyJy8utNa5s+n9EyWXh5lx3Q/mJM40G27J53/El37g0Wlgs2Bt3iuRtYS+w04fH4+oiJa8SDo233UuRRcZne48uYOHQid2SHZtuGzYwxeCO+lJQ6v41p5bf2OjIlhrnCzqEQBRDgdxyl8ezlLSff7t2azrX6KqSREAgP1OpemjShzJOFc2+eRQ37G37cz0kaZ3NPXEkTWPOIriWHbYcoi1MTYxM2/tXAQdJD7ikrWQw/84NPkMfWC0TlM/jXJ4LGRzBtwx9ic+XsNVptSBxJG6y7DoH8kCTtcsHbplN6IPYx/DkALvREp5sf66W6Felhfn1Rl5JFHVFZH7HahI/vU7C/NnfrL8axNrDt6/2AA+/GC+lDx1poGlJ+5tkkcIou4+pXicxR7G0EMp2vJHVt+wFFiHe5x4pnzOFcxN2yID+eDdjMoEVqemXLREYa3xrIuosou/KwUjjcgjOPVFQLtZO7qpD8M7wRdPIk9vScOp8zamUY=
after_failure:
  - git status
  - git diff
