language: groovy
jdk:
  - oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
  - openssl aes-256-cbc -d -a -k $openssl_key -in secring.gpg.enc -out secring.gpg
  - echo signing.password=$gpg_pass >> gradle.properties
  - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
  - unzip gradle-3.5-bin.zip
  - export GRADLE_HOME=$PWD/gradle-3.5
  - export PATH=$GRADLE_HOME/bin:$PATH
script:
  - gradle test --stacktrace
  - gradle uploadArchive --info --stacktrace
env:
  global:
  - secure: FCStFgu8w9OEMvrnGTQhLUBiAMiEkor3WU1JVclPyUltUhrFQ1BW6+GNY74rPiSc+cs4RRtc56YFaSEFOoYrFLN1KfAKIySm7qHhf8+mG+m79SJn1J9I7+eoY5+YndORIgt2UD9FmAfHrAY5miD4ZN9qBTPdAaZ0qHnOF53z7ckSgszC01CTrbJD7l2ZZ+qhgRLuucrkAxSlDpeNbWPHDgPlMHjAMy2W7jjHf8F9NmnrZkoY0AwsYMAAxchVzkh+V85pu9JzGS2Vn4ktgHBb0nqYd6Eh5vQLs+IZWuPRTxt3VCUXiYXBKD0etfGuDNvaUtu1i9MR4NoAuMlPfV01hHii0RNogV76Sex0avgTfObBSJ8YXpoyYsXLqk1Spd/AY4EwVrT7F/dtr/QpRv2ZSBD1N4rzeftPm5biGoSQhHzJPgNmm4AsFC0NCfRxOWldDblPCNm23hi0x/b7mJQkRVYgfqyoCvlYOg9h9xY+enxPqQPN2YDRWXD7B8LgeDGL4h5V5vjQY/uLGSUbn4WKVd9DL3lMcLEJzXDttA9gu4sRpVjqsmYG9T0RUAnfSsdaKI+XrY/tlTzDSIH+RBp0E4mwtnKkraMBDVYzHMec3NZjffv0sN0EW+j4UxB0wDyLGPd0QYuRg5mDIzEpNhX/YqvdW6rfGgI9E2fM37aXhVg=
  - secure: r1800aoyvQ7fURSkV5WyDbZH6YwlRaA3OWxzfthODeDdjWiR5EgfOzpKhtyDVA6QlZBkKN+DTgIW67pFzZXR/MADAL3ychHOvnf0xAY0gcvElQ0DV79hekaTRKVK/4rKfIPexJR9rwvz0wk0CfNyLOZnUAGQGJPUBavVTW/FUHO+iUea9xgzlTWe3ow6MaHmEmsp7t86+jgu86sgAiGK6PWeS6SZ219fzRUkdpaXsqD/JDY+UnmU2FT9k9ObUrXEMyHiJA2TO5kBCo8tPBk33Foo6ZaTq1YWXvyZzDLa/K5fYYH1qBHTAfVDJD/ULDGpAIPyyk2Y9hW7IAb7pPMR/KXCVPMCe9wti9lvmXHgR7afTjtPLUTw0UaFFWKrhV15CnT5xtZcudL6cHjHrOgI8qv8WGWjIAn0ZBfwginktdRi5czr5hVgLdETw9Byoo66EX9H7BBQPvDbJ1E+9BFku7myQPgWzlkvIZassPNzRs2XUrYB2HFphP2KxNqJJL32GKh3XZy5hjqRZRe7oRpu63RH1qmfxg8+SfQzSeY4ezDtJSZFjnt5bR2X5TIemmeJDlw96EcuCBDFFVvvkmIMUzW+t0zpw8wjrDuwAgQTOSjrHwJVFFSsrARkVSJSuoVQ9CJcSI0/W0w9THNmwZXbLr71v78FP8e1a0tHyN8K70M=
