language: groovy
jdk:
  - oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
  - git config --global user.email "erwan@saagie.com"
  - git config --global user.name "erwan"
  - git remote set-url origin git@github.com:saagie/sbt-gradle-plugin.git
  - openssl aes-256-cbc -K $encrypted_837e0722fe3d_key -iv $encrypted_837e0722fe3d_iv -in keys.tar.enc -out keys.tar -d
  - tar xvf keys.tar
  - mv id_rsa_travis ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - cp -fv config ~/.ssh/config
  - echo signing.password=$gpg_pass >> ~/.gradle/gradle.properties
  - echo nexusName=$SONATYPE_USERNAME >> ~/.gradle/gradle.properties
  - echo nexusPassword=$SONATYPE_PASSWORD >> ~/.gradle/gradle.properties
  - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
  - unzip gradle-3.5-bin.zip
  - export GRADLE_HOME=$PWD/gradle-3.5
  - export PATH=$GRADLE_HOME/bin:$PATH
script:
  - gradle test --stacktrace
  - if [ ${TRAVIS_BRANCH} = "master" ]; then
      git checkout master;
      gradle release -Prelease.useAutomaticVersion=true --stacktrace --info;
    else
      gradle uploadArchive --info --stacktrace;
    fi
env:
  global:
  - secure: lq8Na892LjfpLD642K36luhbhqAyz9LN0v0tIvXBF6SpNqLcym+oZYShs4FD2IB0+UI6KPqjhWbH82ebZjjo7on7wb0p/q+BO03b0ND7VQL0XkorgfDqIUUaKsxBTv6u52p7D0Pj+STIpiwv/UMjxL61Kbo7aSONcXemwnn7uFJzenl/7PaqvQNMTbNaHIa8RzHV3Rt/lv0Vv3ixyhfw84cAlqrh/9stkGJG0UsHKG+wWeXjOVOA0BXx61XT2KyVoRVfmMC2W9ubyADxw/cZ2A+ekejUuebCpn0w0wptWYOluk+uLmSgW4TNkqnPHRi9RIgcOOVqlH5e8bE2aqsNO6EJ471e4KQqLzjiWkHLXisHPtyYiMke9M2ubCBwchI6qLt7AswlShgunDD3FoVdnYMmvz0Odql0dyfdgtI7kuA8ub/AS8JEBs0wVeGv/S2Z2fL+0jdbGH7DQgrFeAulQaXIwLaxb1ai0d3ly03Hq7FBOhj8LOD8/MsqDrBXmv/cxgnTNSdA5I4LFMfLPSeuZ4mtPGoc23BbDnUGbTLzglplVyHPGortsfyxWl7JtrfNZeGs87BkQDRRmsgq5XYwB07tdzvPSDXHVyC3r9ZxwCNyqtFoxyY1ePZX6I9aflsQXvkQTt8bGtqyHUPU7qCCRFCNB+/tp1o6wPwQD64NYgI=
  - secure: Fp1tmexIPJ9GJQzXh4qiJRaku3+rhGNi23/9Nk3h8Dp1o23exjV6rGWWWDneD9U60JD6HCbjpSLWdNJyvt89VTXksDk8MHLbjzzKE1/EimxeN76Rjp4ilQHiH8eCX0JCzNyJbFFkeMGiWIaYsv2SEOHAZtdQFXnlFDJ9rsReZsU6IO6y83V8DugcLp6xmHNh0UvqE81fg89WT+Hd//TjvH5TJQMIkj4BI6AzNiMlUoro/NqI8yZfzQtOWl/vtRheqbN9BZWXUG4nBTXDAByzby5YIttJ34HrXA8WPPTJfEHt8Wm+xlU45kVeOfuZIg1bvfW3jG5clGfXdT1RkeLqHDEpmQkbsYoWxARozapqEFhDQ+XhhrkU6WwUsCF/T/ICvHvMWX+24Sb9FNkRavZnt5Awz5SaYMRc+WMhaPD2F/nUxwMvaTToAIgRyrhFawE9CwqF4MwDgRo8UAJ5Zkk2O+tnRMqfJm/hNRgDPzRn5dw7D5NIpZUolMVyzZOQsuu1SEg1xfWC3mU7j2YkQHWYWz3v545xX1UkrAWA/rEDFM34Wx5F9DLjF50eXEvsT31hwNTI8oba4IiM5grAeqh5kL49/FNrvd2HVhdbs+v+o/3sdFgaUSU85+T+CModmDBD4bVWVi2SW+97+UoluqwRZwR20An2YqM3oK9B/yOwH5k=
after_failure:
  - git status
  - git diff
