language: groovy
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
  - openssl aes-256-cbc -d -a -k $openssl_key -in secring.gpg.enc -out secring.gpg
  - echo signing.password=$gpg_pass >> gradle.properties
  - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
  - unzip gradle-3.5-bin.zip
  - export GRADLE_HOME=$PWD/gradle-3.5
  - export PATH=$GRADLE_HOME/bin:$PATH
script:
  - gradle test --stacktrace
  - gradle uploadArchive
